chore: preview isn't automatic
EddieHubCommunity/good-first-issue-finder pull request #38
Opened 2022-01-28 08:18 UTC by krshdev

The preview isn't automatic, this makes it automatic

2022-01-28 08:39 UTC, Cahllagerfeld commented
Thats intentional, because we can't run the app directly when starting. We probably need to even remove the `npm run dev` from the yml-file, as we need to provide an `env` first

2022-01-28 10:46 UTC, krshdev commented
I think we can do that in gitpod itself, there is a prompt which asks you, as said in the gitpodify blog 🤔

2022-01-29 12:46 UTC, Cahllagerfeld commented
I think this PR adds way too much overhead, which isn't necessary, even a new dependency.
What we should just do is removing the automatic start from `command` in the `gitpod.yml`
```diff
tasks:
  - init: npm install # runs during prebuild
    command: |
      export HMR_HOST=`gp url 3000`
-      npm run dev
ports:
  - port: 3000
    onOpen: ignore

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: false
    addBadge: true

vscode:
  extensions:
    - humao.rest-client
    - svelte.svelte-vscode
    - bradlc.vscode-tailwindcss

```

2022-01-29 15:24 UTC, Siddhant-K-code requested changes
- `npm run gitpod`  does not required.
- regarding other file changes, pls add the more description about those changes.

2022-01-29 15:24 UTC, Siddhant-K-code commented on .gitpod.yml
> +      npm run gitpod
```suggestion
      npm run dev
```

will work fine.

2022-01-30 09:02 UTC, krshdev commented on .gitpod.yml
> +      npm run gitpod
This isn't how it has to be fixed 😅

2022-01-30 11:46 UTC, Cahllagerfeld requested changes

2022-01-30 11:46 UTC, Cahllagerfeld commented on package-lock.json
> +  "version": "0.0.1",
theres a newer lockfile already, please update yours or remove it from the commit 👍

2022-02-12 18:35 UTC, Cahllagerfeld approved these changes
Awesome, thank you 💥

2022-02-12 18:35 UTC, merged