Prettier husky
EddieHubCommunity/good-first-issue-finder pull request #415
Opened 2024-08-02 11:27 UTC by Bashamega

Hello:)

I have integrated prettier in husky

2024-08-03 07:17 UTC, Bashamega commented
Hello @eddiejaoude :) Can you please merge this pr

2024-08-03 08:35 UTC, eddiejaoude requested changes
Thank you. Please exclude `CHANGELOG.md` file as this is autogenerated and will cause conflicts

2024-08-03 08:36 UTC, eddiejaoude commented
> Hello @eddiejaoude :) Can you please merge this pr

the extra notifications is not required

@Cahllagerfeld are you able to review?

2024-08-03 08:37 UTC, Bashamega commented
> the extra notifications is not required

Sorry for the notification

2024-08-03 08:41 UTC, eddiejaoude commented
thank you for understanding 👍

2024-08-03 08:43 UTC, Bashamega commented
> Thank you. Please exclude `CHANGELOG.md` file as this is autogenerated and will cause conflicts

It should be excluded because of the prettier ignore.

2024-08-03 08:47 UTC, eddiejaoude commented
> > Thank you. Please exclude `CHANGELOG.md` file as this is autogenerated and will cause conflicts
> 
> It should be excluded because of the prettier ignore.

Oh strange, there are changes to the file https://github.com/EddieHubCommunity/good-first-issue-finder/pull/415/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed

2024-08-03 08:49 UTC, eddiejaoude commented
Strange why the ignore file is not being used, here are the official docs and the filename is correct https://prettier.io/docs/en/ignore.html

2024-08-03 08:52 UTC, Bashamega commented
> Strange why the ignore file is not being used, here are the official docs and the filename is correct https://prettier.io/docs/en/ignore.html

Is it because we are using husky? I don't know how to fix it

2024-08-03 08:59 UTC, eddiejaoude commented
> Is it because we are using husky? I don't know how to fix it

I don't think they are related or causing any issues. I see you have joined EddieHub Discord, let's continue the chat there and publish the conclusion here afterwards

2024-08-07 07:44 UTC, Bashamega commented
Hello:)

I have fixed the issue. The issue was that instead of specifying .prettierignore we were specifying the .gitignore. I have now fixed it.

2024-08-11 06:46 UTC, eddiejaoude commented on .husky/pre-commit
> +npx prettier --ignore-path .prettierignore --check --plugin prettier-plugin-svelte .
```suggestion
npx prettier --ignore-path .prettierignore --check --plugin prettier-plugin-svelte .

```

2024-08-11 06:47 UTC, eddiejaoude commented on CHANGELOG.md
> +
Please ignore this file as it is auto generated

2024-12-05 08:06 UTC, closed without merging